[Model]
# the file and and class name should be included
ModelName = net_relu__addS_phce-add-hidden_skip_try2_wordctc.Transducer
; ModelName = net_relu_mblank_clamp1net.Transducer

[TrainSetting]
# ASR|LM
TrainType = ASR
# custom trainer, will use default if not specified
Trainer = net_relu__addS_phce-add-hidden_skip_try2_wordctc.trainer
OutDir = train_onlywordCTC_v0
;initEncoderModel = /train8/asr mlg/ddye2/RNNT/german/20260114_gongban/10_train_2000_p1_ctc_russianinitmodel/out_train_002/model.init
;initEncoderModel = /train8/asr mlg/ddye2/RNNT/russian/russian_gongban_xd_20250107/7_train_zhy_step2_3/out_train_008/model.iter8.parts
Iter = 20
# which iteration to half learning rate
#Half = 10
Half = 3
HalfHold = 1
InitLearningRate = 0.015
LearningRate = 0.02
# how many iters to print information
Display = 300
# SGD, ADAM
Optimizer = SGD
LookAhead = False
LookAhead_K = 5
LookAhead_Alpha = 0.5
# how many sentences are used to validate, if validation pfile is not specific, will use last part of training pfile
CVSentNum = 1000
# how many iters to perform a validation, set 0 to validate after training
CVInterval = 000
NGpu = 8
RandomSeed = 0
# how many sentences are used to initialize model
InitSent = 300000
# grad norm
ClipGradient = 2
ClipGradient2 = 20
Discount = 0.5
# this will check if loss of current iteration is greater than 10* last iteration, and will skip to prevent divergence
CheckLoss = False
# BMUF
BMUF_ALPHA = 1.0
BMUF_BLR = 1.0
BMUF_BM = 0.875
BMUF_SYNC = 10
# using torchscript, this will accelerate training but may use more gpu memory
JIT = False

[DataSetting]
InitBunchsize = 14000
Bunchsize = 14000
#8192
PadNum = 4
NumFramePredict = 4
PadNumBetweenSent = 1
MaxNumSent = 4096
MaxBatchFrame = 4096
MaxSentFrame = 4096
#DataDir = /yrfs4/asrdictt/zhou2/jobs/chezai/cn_yue/0.down_pfile_merge_syllable/lib_syllable_domain_rnnt
#DataDir = /work1/asrdictt/zhou2/workspace/yewu/chezai_syllable_allnodes/pfile_debug_en_other
; DataDir = /work1/asrdictt/zhou2/workspace/yewu/chezai_syllable_allnodes/pfile_debug_car

DataDir = /raw15/asrdictt/permanent/hjwang11/traindata/mlg20260210/french/car_fr_common_20260209_sp2.0k/lib_fb40
LabelDir = /raw15/asrdictt/permanent/hjwang11/traindata/mlg20260210/french/car_fr_common_20260209_sp2.0k/lib_fb40/mix
; DataDir = /ps6/mkws/ddye2/data/german/RNNT/german_general_8kh_fz_3wh_fbnocmn40_XD_rand_20260116/phone
; LabelDir = /ps6/mkws/ddye2/data/german/RNNT/german_general_8kh_fz_3wh_fbnocmn40_XD_rand_20260116/phone/mix_sp2000

LabelPrefix = lab.pfile$
FeaturePrefix = fea.pfile$
# using $ to indicate part index, eg: lab.pfile0 -> lab.pfile$

ShuffleBatch = True
ShuffleSeq = True
Npart = 10

NormFile = /raw15/asrdictt/permanent/hjwang11/traindata/mlg20260210/french/car_fr_common_20260209_sp2.0k/lib_fb40/fea.norm0
#NormFile = /ps6/mkws/ddye2/data/german/RNNT/german_general_8kh_fz_3wh_fbnocmn40_XD_rand_20260116/phone/fea.norm0
#NormFile = /work1/asrdictt/zhou2/workspace/yewu/chezai_syllable_allnodes/lib_fbnocmn40/fea.norm.normal
# empty or dirname, the data used to perform validation
; ValidationDatadir = /yrfs4/asrdictt/hjwang11/multilingual/indonesian/rnnt/am/testset/geely/NO1579_indonesian_chezai_geely_tests
; ValidationFeature = fea.pfile0
; ValidationLabel = lab.pfile0

ValidationDatadir = /raw15/asrdictt/permanent/hjwang11/traindata/mlg20260210/french/car_fr_common_20260209_sp2.0k/lib_fb40/mix
ValidationFeature = fea.pfile0
ValidationLabel = lab.pfile0

[PartDistribution]